[build-system]
requires = [
    "setuptools", 
    "wheel",
]

[tool.flakeheaven]
base = "https://raw.githubusercontent.com/quipucords/linting/main/base-flakeheaven.toml"
baseline = ".flakeheaven-baseline"

[tool.pylint.master]
load-plugins = ["pylint_pytest"]

[tool.pytest.ini_options]
pythonpath = "qpc"
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
    "tests_*.py",
]
